### ISSUE TITLE
List of people who support a project

### ISSUE THREAD

**Issue by uphf-jerome** [ulule/developers.ulule.com#133]
Hello
It is currently possible in the "Backers" section of a project to consult the list of people who back a project, the reward selected and when it was paid ... all without a particular connection.
Are there any plans to make this information available in the public API data?

**Comment by yansal** [comment]
Hello @uphf-jerome and thank you for considering using Ulule API,

This information is available in Ulule API : have a look at the `GET /projects/:id/supporters` endpoint (https://developers.ulule.com/docs/ulule-api/#list-all-project-supporters), and the `latest_project_comment` and `latest_project_order` extra fields (https://developers.ulule.com/docs/ulule-api/#user-resource).

Let us know if you need help using Ulule API.

**Comment by uphf-jerome** [comment]
Thank you very much, I had not seen this information in the documentation. I will look at this.
