### ISSUE TITLE
Sandbox and/or test account for project owner

### ISSUE THREAD

**Issue by uphf-jerome** [ulule/developers.ulule.com#134]
Hello

Is there a test account to test the API with a "project owner" profile? This is to work on the answers from fictitious projects

And is there a sandbox with fictitious projects in different states, with fake buyer accounts, ... in order to test the different endpoints linked to the project owner

It is possible to test the whole API without identification, but some options require a "project owner" account, and not everyone has one

Thank you for the feedback

**Comment by yansal** [comment]
Please contact us at api@ulule.com explaining your need in detail.
